#server:
#  port: 8090
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
    register-with-eureka: false
  instance:
    appname: gateway
    preferIpAddress: true
