server:
  port: 8088
spring:
  profiles:
    active: native
  security:
    user:
      name: ${config.user:test}
      password: ${config.user:test}
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared
